name: example-of-working-directory
run-name: ${{ github.actor }} is trying to understand github actions

on:
  workflow_dispatch:

jobs:
  print-working-directory:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: subdir

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: step1
        run: |
          ls -la
          pwd
          cd ..
          pwd

      - name: step2
        run: |
          pwd
  
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g bats
